# test script checking that all installed/required libraries are present
library(argparser)
library(bigreadr)
library(bigsnpr)
library(devtools)
library(data.table)
library(dplyr)
library(ggplot2)
library(grDevices)
library(methods)
library(optparse)
library(R.utils)
library(RColorBrewer)
library(stringr)
library(tidyverse)
library(tools)
